# NumPy Exercises
due to Petr Romov

In [1]:
import numpy as np

SELF. Generate a matrix with 1000 rows and 50 columns, elements being drawn from normal distribution $\mathcal{N}(1, 10)$. Specify random seed to make the result reproducible. Use http://docs.scipy.org/doc/numpy/reference/routines.random.html

In [57]:
np.random.seed(1)
sigma = 10
mu = 1
a = sigma*np.random.randn(1000,50)+mu

SELF. Normalize the matrix: subtract from each column its mean and divide by the standard deviation. I suggest np.mean, np.std with axis parameter.

In [58]:
print(a.mean(axis=0))
print(a.std(axis=0))

from sklearn import preprocessing
a_scaled = preprocessing.scale(a)
print(a_scaled.mean(axis=0))
print(a_scaled.std(axis=0))

[ 1.63541569  0.73525786  1.04773795  0.72033988  1.15138463  0.74848509
  1.16593862  1.01639817  0.90760091  1.34472101  0.93169785  0.3163826
  0.70117251  0.69139279  0.99524087  1.15113457  1.23365016  1.15718478
  0.91678017  0.40631877  0.87633603  0.79656176  0.55744485  1.82326403
  1.47065636  0.75238181  1.30392293  0.84200847  1.38419088  0.67932334
  1.09717756  1.88106544  1.28934718  0.96066564  1.47383238  0.85131972
  1.1763672   0.56854632  1.30621012  1.39181938  1.60952353  1.37145601
  0.96861651  1.80645417  0.77647937  0.94776415  0.32605793  0.85334034
  1.10871678  0.66915977]
[ 10.22692105   9.97634029  10.14496899  10.18549434   9.89265693
   9.69957476  10.27382684   9.83716519  10.15554778  10.54286191
  10.04645252  10.23130293  10.26734307   9.57633924  10.08167762
   9.80427445  10.27898735  10.03674698  10.00334091  10.2583895
  10.47239728   9.97644378  10.22510736   9.81771186  10.38669795
   9.9046711    9.99120149   9.78888859   9.63685548  10.24180

Print for the following matrix row numbers for those rows, where element sum is greater than 10. I suggest np.sum and np.nonzero

In [31]:
Z = np.array([[4, 5, 0],
              [1, 9, 3],
              [5, 1, 1],
              [3, 3, 3],
              [9, 9, 9],
              [4, 7, 1]])

Z[Z.sum(axis=1) > 10]

array([[1, 9, 3],
       [9, 9, 9],
       [4, 7, 1]])

Write a python function to get N largest values from a 1D or 2D array. It should accept as a mandatory parameter N - the number of values to return and optional axis. If axis is not specified, use the flattened array, if specified - return a matrix with N maximum values for each row or column (depends on the axis). BONUS - allow arrays of arbitary dimensions, axis should work as in https://docs.scipy.org/doc/numpy/reference/generated/numpy.amax.html#numpy.amax

In [85]:
def nmax(a, n, axis=None):
    if axis is 'row':
        return np.sort(a, axis=1)[:,-n:]
    if axis is 'col':
        return np.sort(a, axis=0)[-n:,:]
    
    return np.sort(a.ravel())[-n:]
a = np.random.randn(100)
print(Z)
nmax(Z,6,axis='col')


[[4 5 0]
 [1 9 3]
 [5 1 1]
 [3 3 3]
 [9 9 9]
 [4 7 1]]


array([[1, 1, 0],
       [3, 3, 1],
       [4, 5, 1],
       [4, 7, 3],
       [5, 9, 3],
       [9, 9, 9]])